switch to rg-d (#891)

diff --git a/bin/run-clara b/bin/run-clara
--- a/bin/run-clara
+++ b/bin/run-clara
@@ -34,6 +34,7 @@ do
         c) CLARA_HOME=$OPTARG ;;
         t) threads=$OPTARG && echo $threads | grep -q -E '^[0-9]+$' || error "-t must be an integer, threads" ;;
         n) nevents="-e $OPTARG" && echo "$nevents" | grep -q -E '^-e [0-9]+$' || error "-n must be an integer, events" ;;
+        g) memory_gb="-e $OPTARG" && echo "$memory_gb" | grep -q -E '^-e [0-9]+$' || error "-g must be an integer, GB of memory" ;;
         m) merge=1 ;;
         q) quiet=1 ;;
         h) echo -e "\n$usage" && echo -e $info && exit 0 ;;
@@ -41,6 +42,9 @@ do
 done
 shift $((OPTIND-1))
 inputs=$@
+
+# Configure JVM -Xmx memory setting:
+[ -z ${memory_gb+x} ] && memory_gb=$((threads+2))
 
 # Check configuration:
 [ $# -lt 1 ] && error "Input data files are required"
@@ -72,7 +76,7 @@ done
 [ $(cat $CLARA_USER_DATA/filelist.txt | wc -l) -gt 0 ] || error "Found no input files"
 
 # Set some JVM options:
-export JAVA_OPTS="$JAVA_OPTS -Xmx${threads}g -XX:+IgnoreUnrecognizedVMOptions"
+export JAVA_OPTS="$JAVA_OPTS -Xmx${memory_gb}g -XX:+IgnoreUnrecognizedVMOptions"
 export JAVA_OPTS="$JAVA_OPTS -Djava.io.tmpdir=$CLARA_USER_DATA -Dorg.sqlite.tmpdir=$CLARA_USER_DATA"
 # Set verbosity:
 [ -z ${quiet+x} ] && stub=fine || stub=info
